apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: arieszhang/jenkins-casc:0.2.11
          resources:
              requests:
                memory: "1024Mi"
                cpu: "250m"
              limits:
                memory: "2048Mi"
                cpu: "500m"
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
            - name: CASC_JENKINS_CONFIG
              value: "/var/jenkins_home/config/jenkins.yaml"
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-config
              mountPath: /var/jenkins_home/config
            - name: jenkins-init
              mountPath: /var/jenkins_home/init.groovy.d
      volumes:
        - name: jenkins-home
          emptyDir: {}
        - name: jenkins-config
          configMap:
              defaultMode: 420
              name: jenkins-config
        - name: jenkins-init
          configMap:
              defaultMode: 420
              name: jenkins-init

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - port: 50000
      targetPort: 50000

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jenkins.home
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
data:
  jenkins.yaml: |
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      clouds:
      - kubernetes:
          name: "kube-docker-desktop"
          serverUrl: "https://kubernetes.docker.internal:6443"
          jenkinsUrl: "http://jenkins:8080"
          jenkinsTunnel: "jenkins-jnlp:50000"
          skipTlsVerify: true
      securityRealm:
        local:
          allowsSignup: false
          users:
          - id: admin
            password: ${JENKINS_ADMIN_PASSWORD:-P@ssw0rd}
      disableRememberMe: true
      crumbIssuer: "standard"
      remotingSecurity:
        enabled: true
    unclassified:
      location:
        adminAddress: "address not configured yet <nobody@nowhere>"
        url: "http://localhost:30000/"  
    tool:
      git:
        installations:
        - home: "git"
          name: "Default"
    jobs:
      - script: >
          freeStyleJob('example') {
            steps {
                shell('echo Hello World!')
            }
          }
      - script: >
          pipelineJob('Kubernetes build') {
              definition {
                  cpsScm {
                      scm {
                        git {
                            remote {
                                github('aries-zhang/jenkins-pipeline-example')
                            }
                        }
                        scriptPath('deploy.jenkins')
                      }
                  }
              }
          }
        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-init
data:
  01-start.groovy: |
    import jenkins.model.Jenkins;
    println("doQuietDown");
    Jenkins.instance.doQuietDown();
  xx-end.groovy: |
    import jenkins.model.Jenkins;
    println("doCancelQuietDown");
    Jenkins.instance.doCancelQuietDown()

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jenkins.aries.me
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
