apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: arieszhang/jenkins-casc:0.1.3
          resources:
              requests:
                memory: "1024Mi"
                cpu: "250m"
              limits:
                memory: "2048Mi"
                cpu: "500m"
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
            - name: CASC_JENKINS_CONFIG
              value: "/var/jenkins_home/config/jenkins.yaml"
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-config
              mountPath: /var/jenkins_home/config
      volumes:
        - name: jenkins-home
          emptyDir: {}
        - name: jenkins-config
          configMap:
              defaultMode: 420
              name: jenkins-config

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
data:
  jenkins.yaml: |
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      securityRealm:
        local:
          allowsSignup: false
          users:
          - id: admin
            password: ${JENKINS_ADMIN_PASSWORD:-P@ssw0rd}
      disableRememberMe: true
      crumbIssuer: "standard"
    tool:
      git:
        installations:
        - home: "git"
          name: "Default"
    jobs:
      - script: >
          freeStyleJob('example') {
            steps {
                shell('echo Hello World!')
            }
          }
