jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${JENKINS_ADMIN_PASSWORD:-P@ssw0rd}
  disableRememberMe: true
  crumbIssuer: "standard"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
jobs:
  - script: >
      freeStyleJob('example') {
        steps {
            shell('echo Hello World!')
        }
      }