name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  VERSION: 0.2.${GITHUB_RUN_NUMBER}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: 'docker/build-push-action@v1'
      with:
        repository     : 'arieszhang/jenkins-casc'
        username       : ${{ secrets.DOCKERHUB_USERNAME }}
        password       : ${{ secrets.DOCKERHUB_PASSWORD }}
        tags           : ${{ env.VERSION }}, latest
        add_git_labels : true
        tag_with_ref   : true
        tag_with_sha   : true
